services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  django_gunicorn:
    container_name: django_gunicorn
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  nginx:
    container_name: django_nginx
    build:
      context: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:8000"
    depends_on:
      - django_gunicorn

volumes:
  static:
  postgres_data: